// This C++ header file was generated by the TTCN-3 compiler
// of the TTCN-3 Test Executor version CRL 113 200/6 R6B
// for U-ERICSSON\ethbaat (ethbaat@HU-00000670) on Thu Feb 20 17:43:37 2020

// Copyright (c) 2000-2019 Ericsson Telecom AB

// Do not edit this file unless you know what you are doing.

#ifndef JsonEncDecFunctions_HH
#define JsonEncDecFunctions_HH

#ifdef TITAN_RUNTIME_2
#error Generated code does not match with used runtime.\
 Code was generated without -R option but -DTITAN_RUNTIME_2 was used.
#endif

/* Header file includes */

#include <TTCN3.hh>
#include "JsonBasicTypes.hh"

#if TTCN3_VERSION != 60601
#error Version mismatch detected.\
 Please check the version of the TTCN-3 compiler and the base library.\
 Run make clean and rebuild the project if the version of the compiler changed recently.
#endif

#ifndef WIN32
#error This file should be compiled on WIN32
#endif

namespace JsonEncDecFunctions {

/* Function prototypes */

extern BITSTRING f__json__enc__i2bs(const INTEGER& i);
extern BITSTRING f__json__enc__f2bs(const FLOAT& f);
extern BITSTRING f__json__enc__e2bs(const JsonBasicTypes::E__json& f);
extern BITSTRING f__json__enc__b2bs(const BOOLEAN& f);
extern BITSTRING f__json__enc__bs2bs(const BITSTRING& f);
extern BITSTRING f__json__enc__hs2bs(const HEXSTRING& f);
extern BITSTRING f__json__enc__os2bs(const OCTETSTRING& f);
extern BITSTRING f__json__enc__cs2bs(const CHARSTRING& f);
extern BITSTRING f__json__enc__ucs2bs(const UNIVERSAL_CHARSTRING& f);
extern BITSTRING f__json__enc__ai3tobs(const JsonBasicTypes::AI3__json& f);
extern BITSTRING f__json__enc__v2bs(const VERDICTTYPE& f);
extern BITSTRING f__json__enc__r2bs(const JsonBasicTypes::R__json& f);
extern BITSTRING f__json__enc__roi2bs(const JsonBasicTypes::RoI__json& f);
extern BITSTRING f__json__enc__s2bs(const JsonBasicTypes::S__json& f);
extern BITSTRING f__json__enc__soi2bs(const JsonBasicTypes::SoI__json& f);
extern BITSTRING f__json__enc__u2bs(const JsonBasicTypes::U__json& f);
extern OCTETSTRING f__json__enc__i2os(const INTEGER& i);
extern OCTETSTRING f__json__enc__f2os(const FLOAT& f);
extern OCTETSTRING f__json__enc__e2os(const JsonBasicTypes::E__json& f);
extern OCTETSTRING f__json__enc__b2os(const BOOLEAN& f);
extern OCTETSTRING f__json__enc__bs2os(const BITSTRING& f);
extern OCTETSTRING f__json__enc__hs2os(const HEXSTRING& f);
extern OCTETSTRING f__json__enc__os2os(const OCTETSTRING& f);
extern OCTETSTRING f__json__enc__cs2os(const CHARSTRING& f);
extern OCTETSTRING f__json__enc__ucs2os(const UNIVERSAL_CHARSTRING& f);
extern OCTETSTRING f__json__enc__ai3toos(const JsonBasicTypes::AI3__json& f);
extern OCTETSTRING f__json__enc__v2os(const VERDICTTYPE& f);
extern OCTETSTRING f__json__enc__r2os(const JsonBasicTypes::R__json& f);
extern OCTETSTRING f__json__enc__roi2os(const JsonBasicTypes::RoI__json& f);
extern OCTETSTRING f__json__enc__s2os(const JsonBasicTypes::S__json& f);
extern OCTETSTRING f__json__enc__soi2os(const JsonBasicTypes::SoI__json& f);
extern OCTETSTRING f__json__enc__u2os(const JsonBasicTypes::U__json& f);
extern INTEGER f__json__dec__bs2i(const BITSTRING& p);
extern FLOAT f__json__dec__bs2f(const BITSTRING& p);
extern JsonBasicTypes::E__json f__json__dec__bs2e(const BITSTRING& p);
extern BOOLEAN f__json__dec__bs2b(const BITSTRING& p);
extern BITSTRING f__json__dec__bs2bs(const BITSTRING& p);
extern HEXSTRING f__json__dec__bs2hs(const BITSTRING& p);
extern OCTETSTRING f__json__dec__bs2os(const BITSTRING& p);
extern CHARSTRING f__json__dec__bs2cs(const BITSTRING& p);
extern UNIVERSAL_CHARSTRING f__json__dec__bs2ucs(const BITSTRING& p);
extern JsonBasicTypes::AI3__json f__json__dec__bstoai3(const BITSTRING& p);
extern VERDICTTYPE f__json__dec__bs2v(const BITSTRING& p);
extern JsonBasicTypes::R__json f__json__dec__bs2r(const BITSTRING& p);
extern JsonBasicTypes::RoI__json f__json__dec__bs2roi(const BITSTRING& p);
extern JsonBasicTypes::S__json f__json__dec__bs2s(const BITSTRING& p);
extern JsonBasicTypes::SoI__json f__json__dec__bs2soi(const BITSTRING& p);
extern JsonBasicTypes::U__json f__json__dec__bs2u(const BITSTRING& p);
extern INTEGER f__json__dec__os2i(const OCTETSTRING& p);
extern FLOAT f__json__dec__os2f(const OCTETSTRING& p);
extern JsonBasicTypes::E__json f__json__dec__os2e(const OCTETSTRING& p);
extern BOOLEAN f__json__dec__os2b(const OCTETSTRING& p);
extern BITSTRING f__json__dec__os2bs(const OCTETSTRING& p);
extern HEXSTRING f__json__dec__os2hs(const OCTETSTRING& p);
extern OCTETSTRING f__json__dec__os2os(const OCTETSTRING& p);
extern CHARSTRING f__json__dec__os2cs(const OCTETSTRING& p);
extern UNIVERSAL_CHARSTRING f__json__dec__os2ucs(const OCTETSTRING& p);
extern JsonBasicTypes::AI3__json f__json__dec__ostoai3(const OCTETSTRING& p);
extern VERDICTTYPE f__json__dec__os2v(const OCTETSTRING& p);
extern JsonBasicTypes::R__json f__json__dec__os2r(const OCTETSTRING& p);
extern JsonBasicTypes::RoI__json f__json__dec__os2roi(const OCTETSTRING& p);
extern JsonBasicTypes::S__json f__json__dec__os2s(const OCTETSTRING& p);
extern JsonBasicTypes::SoI__json f__json__dec__os2soi(const OCTETSTRING& p);
extern JsonBasicTypes::U__json f__json__dec__os2u(const OCTETSTRING& p);

/* Global variable declarations */

extern TTCN_Module module_object;

} /* end of namespace */

#endif
