// This Test Port skeleton source file was generated by the
// TTCN-3 Compiler of the TTCN-3 Test Executor version CRL 113 200/6 R4A
// for Botond Baranyi (ebotbar@ubuntuVB) on Mon May  7 17:31:08 2018

// Copyright (c) 2000-2018 Ericsson Telecom AB

// You may modify this file. Complete the body of empty functions and
// add your member functions here.

#include "PT4.hh"

namespace PortTranslation {

PT4::PT4(const char *par_port_name)
	: PT4_BASE(par_port_name)
{

}

PT4::~PT4()
{

}

void PT4::set_parameter(const char * /*parameter_name*/,
	const char * /*parameter_value*/)
{

}

/*void PT4::Handle_Fd_Event(int fd, boolean is_readable,
	boolean is_writable, boolean is_error) {}*/

void PT4::Handle_Fd_Event_Error(int /*fd*/)
{

}

void PT4::Handle_Fd_Event_Writable(int /*fd*/)
{

}

void PT4::Handle_Fd_Event_Readable(int /*fd*/)
{

}

/*void PT4::Handle_Timeout(double time_since_last_call) {}*/

void PT4::user_map(const char * /*system_port*/)
{

}

void PT4::user_unmap(const char * /*system_port*/)
{

}

void PT4::user_start()
{

}

void PT4::user_stop()
{

}

void PT4::outgoing_send(const CHARSTRING& /*send_par*/)
{
  TTCN_Runtime::setverdict(FAIL, "The port mapping was not done in translation mode.");
}

} /* end of namespace */

