// This C++ header file was generated by the TTCN-3 compiler
// of the TTCN-3 Test Executor version CRL 113 200/6 R1A
// for Botond Baranyi (ebotbar@ebotbar-VirtualBox) on Wed Mar 22 12:14:17 2017

// Copyright (c) 2000-2017 Ericsson Telecom AB

// Do not edit this file unless you know what you are doing.

#ifndef TemplateConcatUniunichar_HH
#define TemplateConcatUniunichar_HH

#ifdef TITAN_RUNTIME_2
#error Generated code does not match with used runtime.\
 Code was generated without -R option but -DTITAN_RUNTIME_2 was used.
#endif

/* Header file includes */

#include <TTCN3.hh>
#include "Types.hh"

#if TTCN3_VERSION != 60100
#error Version mismatch detected.\
 Please check the version of the TTCN-3 compiler and the base library.\
 Run make clean and rebuild the project if the version of the compiler changed recently.
#endif

#ifndef LINUX
#error This file should be compiled on LINUX
#endif

namespace TemplateConcatUniunichar {

/* Function prototypes */

extern verdicttype testcase_tc__unichar__t__values(boolean has_timer, double timer_value);

/* Global variable declarations */

extern const UNIVERSAL_CHARSTRING& c__unichar;
extern const UNIVERSAL_CHARSTRING_template& t__unichar;
extern const UNIVERSAL_CHARSTRING_template& t__unichar1;
extern const UNIVERSAL_CHARSTRING& c__unichar1__exp;
extern const UNIVERSAL_CHARSTRING_template& t__unichar2;
extern const UNIVERSAL_CHARSTRING& c__unichar2__exp;
extern const UNIVERSAL_CHARSTRING_template& t__unichar3;
extern const UNIVERSAL_CHARSTRING& c__unichar3__exp;
extern const UNIVERSAL_CHARSTRING_template& t__unichar4;
extern const UNIVERSAL_CHARSTRING& c__unichar4__exp;
extern TTCN_Module module_object;

} /* end of namespace */

#endif
